spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:todolist
    username: jayden_chris
    password: P@ssw0rd
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
  #    show-sql: true
  h2:
    console.enabled: true

server:
  port: 8080